# Generated by Django 4.1 on 2024-11-20 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id_model', models.IntegerField(primary_key=True, serialize=False)),
                ('id_dataset', models.IntegerField()),
                ('start_date', models.CharField(max_length=15)),
                ('finish_date', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('email_recover', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_plan', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id_dataset', models.IntegerField(primary_key=True, serialize=False)),
                ('upload_date', models.CharField(max_length=15)),
                ('name_dataset', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=6, max_digits=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.user')),
            ],
        ),
    ]
