# Generated by Django 4.2.16 on 2025-03-17 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('firstlastname', models.CharField(max_length=50)),
                ('secondlastname', models.CharField(max_length=50)),
                ('email_recover', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='name_dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='email_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.user'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstlastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondlastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id_dataset',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='upload_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='id_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.dataset'),
        ),
        migrations.AlterField(
            model_name='model',
            name='id_model',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type_plan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
