# Generated by Django 4.2.16 on 2025-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_dataset_email_id_alter_model_id_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporal',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
