# Generated by Django 4.2.16 on 2025-03-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='email_id',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
