# Generated by Django 4.2.16 on 2025-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_model_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiperparameters_Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('prime_stack', models.CharField(max_length=70)),
                ('criterion', models.IntegerField()),
                ('splitter', models.IntegerField()),
                ('max_depth', models.FloatField()),
                ('min_samples_split', models.FloatField()),
                ('min_leaf_split', models.FloatField()),
                ('max_leaf_nodes', models.FloatField()),
                ('min_impurity_decrease', models.FloatField()),
                ('max_features', models.FloatField()),
                ('random_state', models.FloatField()),
                ('ccp_alpha', models.FloatField()),
                ('class_weight', models.FloatField()),
            ],
        ),
    ]
