# Generated by Django 4.2.16 on 2025-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_hiperparameters_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiperparameters_tree',
            name='email_id',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
