# Generated by Django 4.2.16 on 2025-03-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_hiperparameters_tree_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiperparameters_KNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(default='example@example.com', max_length=254)),
                ('model_id', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('prime_stack', models.CharField(max_length=70)),
                ('n_neighbors', models.FloatField()),
                ('weights', models.FloatField()),
                ('algorithm', models.IntegerField()),
                ('leaf_size', models.FloatField()),
                ('p', models.FloatField()),
                ('metric', models.IntegerField()),
            ],
        ),
    ]
