# Generated by Django 4.2.16 on 2025-03-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0009_hiperparameters_knn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiperparameters_RandomForest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(default='example@example.com', max_length=254)),
                ('model_id', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('prime_stack', models.CharField(max_length=70)),
                ('n_estimators', models.FloatField()),
                ('criterion', models.IntegerField()),
                ('max_depth', models.FloatField()),
                ('min_samples_split', models.FloatField()),
                ('min_samples_leaft', models.FloatField()),
                ('max_features', models.FloatField()),
                ('bootstrap', models.IntegerField()),
                ('oob_score', models.IntegerField()),
                ('max_samples', models.FloatField()),
                ('random_state', models.FloatField()),
                ('class_weight', models.IntegerField()),
            ],
        ),
    ]
