# Generated by Django 4.2.16 on 2025-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0010_hiperparameters_randomforest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiperparameters_randomforest',
            name='bootstrap',
        ),
        migrations.AddField(
            model_name='hiperparameters_randomforest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
