# Generated by Django 4.2.16 on 2025-03-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0011_remove_hiperparameters_randomforest_bootstrap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiperparameters_randomforest',
            old_name='status',
            new_name='bootstrap',
        ),
    ]
