# Generated by Django 4.2.16 on 2025-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0012_rename_status_hiperparameters_randomforest_bootstrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiperparameters_randomforest',
            name='max_samples',
            field=models.FloatField(null=True),
        ),
    ]
