# Generated by Django 4.2.16 on 2025-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0013_alter_hiperparameters_randomforest_max_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='primeStack',
            field=models.CharField(default='stack', max_length=70),
        ),
    ]
