# Generated by Django 4.2.16 on 2025-03-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0014_model_primestack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
