# Generated by Django 4.2.16 on 2025-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0015_alter_model_finish_date_alter_model_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiperparameters_knn',
            name='metric',
            field=models.CharField(default='minkowski', max_length=15),
        ),
    ]
