# Generated by Django 4.2.16 on 2025-03-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0016_alter_hiperparameters_knn_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiperparameters_knn',
            name='algorithm',
        ),
    ]
