# Generated by Django 4.2.16 on 2025-04-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0018_hiperparameters_knn_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='type_cr',
            field=models.IntegerField(default=0),
        ),
    ]
