# Generated by Django 4.2.16 on 2025-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0019_model_type_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiperparameters_randomforest',
            name='max_features',
            field=models.CharField(max_length=50),
        ),
    ]
